### ISSUE TITLE
Target temp not updating

### ISSUE THREAD

**Issue by wrender** [prairieapps/py-schluter#2]
hey @prairieapps   .  Not sure if you are seeing this problem, but recently my schluter thermostat doesn't show the correct target temp in home assistant.  For example, if I change it to 5C, and then login to their portal at https://ditra-heat-e-wifi.schluter.com/#thermostats  It shows 5C,  but then if I go to developer tools in home assistant, and show the state, it shows something like:  temperature: 21

I'm not sure if this would be a state problem on home assistants end, or problem with the api code?

**Comment by prairieapps** [comment]
Hi @wrender , I noticed this issue as well very recently. My suspicion is something may have changed with the Schluter API recently.

**Comment by wrender** [comment]
Ok. Interesting. Do they have a changelog, or documentation?  I might be able to help.

**Comment by wrender** [comment]
It looks like it maybe be an issue completely on their end. If I set the temperature manually through the web interface at https://ditra-heat-e-wifi.schluter.com/#thermostats  it also does not update on the physical thermostat.

**Comment by prairieapps** [comment]
Interesting, good diagnosis. That leads me to think it's an issue on their end as well. It may be worth reaching out to their support to notify them of the problem.

**Comment by wrender** [comment]
It seems to still be broke. I've sent them a message on facebook.

**Comment by wrender** [comment]
I called them. Although they didn't confirm anything, it seems they have fixed the issue. It started working again today.
